---
- include: tasks/init.yml
  become: true
  become_user: root

- include: tasks/env.yml
  become: true
  become_user: "{{ app_puma_exec_user }}"

- include: tasks/config.yml
  become: true
  become_user: root

- include: tasks/finish.yml
  become: true
  become_user: root
